[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"


[[language]]
name = "python"

[language-server.pylsp.config.pylsp]
jedi.extra_paths = [
  "/Users/his-am-off/arc/arcadia",
  "/Users/his-am-off/arc/arcadia/yt/python",
  "/Users/his-am-off/arc/arcadia/contrib/libs/protobuf/python",
  "/Users/his-am-off/arc/arcadia/contrib/python"
]
